name: Publish Documentation

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Generate Documentation
        run: ./gradlew dokkaGenerateModuleHTML

      - name: Debug: List build directory
        run: |
          echo "Build directory structure:"
          find build -type d
          echo "Dokka output contents:"
          find build/dokka-module -type f || true

      - name: Locate and Copy Documentation
        run: |
          # Check multiple possible locations
          if [ -d "build/dokka-module/html" ]; then
            echo "Found HTML documentation at build/dokka-module/html"
            mkdir -p docs
            cp -R build/dokka-module/html/* docs/
          elif [ -d "build/dokka/html" ]; then
            echo "Found HTML documentation at build/dokka/html"
            mkdir -p docs
            cp -R build/dokka/html/* docs/
          elif [ -d "build/dokka" ]; then
            echo "Found documentation at build/dokka"
            mkdir -p docs
            cp -R build/dokka/* docs/
          else
            echo "Documentation not found! Directory listing:"
            ls -R build
            exit 1
          fi
          
          # Verify docs content
          echo "Copied documentation contents:"
          ls -R docs
          
          # Create necessary files for GitHub Pages
          touch docs/.nojekyll
          echo "# Documentation" > docs/README.md
          echo "Automatically generated documentation: [View Docs](index.html)" >> docs/README.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: false
          force_orphan: true