name: Publish Documentation

on:
    push:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: 'gradle'

            - name: Make gradlew executable
              run: chmod +x gradlew

            - name: Generate Documentation
              run: |
                  # Run documentation generation with verbose output
                  ./gradlew dokkaGenerateModuleHTML --console=verbose

            - name: Copy Documentation
              run: |
                  # Create docs directory
                  mkdir -p docs
                  
                  # Copy from the correct path based on previous output
                  cp -R build/dokka/html/* docs/ || \
                  cp -R build/dokka-module/html/module/* docs/ || \
                  cp -R build/dokka/* docs/ || \
                  { echo "No documentation found in expected locations!"; exit 1; }
                  
                  # Create GitHub Pages configuration
                  touch docs/.nojekyll
                  echo "# Documentation" > docs/README.md
                  echo "Automatically generated documentation: [View Docs](index.html)" >> docs/README.md

            - name: Verify Documentation
              run: |
                  echo "Documentation contents:"
                  ls -R docs
                  echo "Index file exists: $(test -f docs/index.html && echo YES || echo NO)"
                  echo "Package file count: $(find docs/com -type f 2>/dev/null | wc -l)"

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs
                  keep_files: false
                  force_orphan: true