- name: Generate Documentation
  run: ./gradlew dokkaGenerateModuleHTML

- name: List Dokka Output (Debug)
  run: ls -lR build/dokka

- name: Deploy to GitHub Pages
  uses: peaceiris/actions-gh-pages@v3
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    publish_dir: ./build/dokka/moduleHtml
