name: Publish Documentation

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Generate Documentation
        run: |
          # Run Dokka and capture output
          ./gradlew dokkaGenerateModuleHTML || true
          echo "Dokka generation completed"

      - name: Find Documentation Files
        run: |
          # Search for all HTML files in build directory
          mkdir -p docs
          find build -name '*.html' -exec cp --parents {} docs/ \;
          
          # If no HTML files found, create placeholder
          if [ -z "$(find docs -name '*.html')" ]; then
            echo "No documentation found! Creating placeholder"
            echo "<html><body><h1>Documentation Not Generated</h1></body></html>" > docs/index.html
          fi
          
          # Create necessary files for GitHub Pages
          touch docs/.nojekyll
          echo "# Documentation" > docs/README.md
          echo "Automatically generated documentation: [View Docs](index.html)" >> docs/README.md

      - name: Verify Documentation Files
        run: |
          echo "Documentation files:"
          find docs -type f
          echo "File count: $(find docs -type f | wc -l)"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: false
          force_orphan: true