name: Publish Documentation

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Fix Dokka Configuration
        run: |
          # Add Dokka plugin to build.gradle.kts if missing
          if ! grep -q "id(\"org.jetbrains.dokka\")" build.gradle.kts; then
            echo "Adding Dokka plugin to build.gradle.kts"
            sed -i '/plugins {/a \    id("org.jetbrains.dokka") version "1.9.20"' build.gradle.kts
          fi
          
          # Configure Dokka if missing
          if ! grep -q "dokkaHtml" build.gradle.kts; then
            echo "Adding Dokka configuration to build.gradle.kts"
            # Append configuration line by line
            echo "" >> build.gradle.kts
            echo "tasks.dokkaHtml.configure {" >> build.gradle.kts
            echo "    outputDirectory.set(file(\"\$buildDir/dokka\"))" >> build.gradle.kts
            echo "    moduleName.set(\"Octofault\")" >> build.gradle.kts
            echo "    dokkaSourceSets {" >> build.gradle.kts
            echo "        named(\"main\") {" >> build.gradle.kts
            echo "            includes.from(\"src/main/kotlin\")" >> build.gradle.kts
            echo "            jdkVersion.set(17)" >> build.gradle.kts
            echo "            sourceLink {" >> build.gradle.kts
            echo "                localDirectory.set(file(\"src/main/kotlin\"))" >> build.gradle.kts
            echo "                remoteUrl.set(uri(\"https://github.com/IKKNIGHT/Octofault/tree/main/src/main/kotlin\").toURL())" >> build.gradle.kts
            echo "                remoteLineSuffix.set(\"#L\")" >> build.gradle.kts
            echo "            }" >> build.gradle.kts
            echo "        }" >> build.gradle.kts
            echo "    }" >> build.gradle.kts
            echo "}" >> build.gradle.kts
          fi

      - name: Generate Documentation
        run: |
          ./gradlew dokkaHtml --stacktrace || \
          { 
            echo "::error::Dokka generation failed!";
            ./gradlew tasks --all;
            exit 1;
          }

      - name: Copy Documentation
        run: |
          mkdir -p docs
          cp -R build/dokka/* docs/ || \
          { 
            echo "::error::Documentation not found!";
            find build -name 'dokka*' -print;
            exit 1;
          }
          
          touch docs/.nojekyll
          echo "# Documentation" > docs/README.md
          echo "Automatically generated documentation: [View Docs](index.html)" >> docs/README.md
          echo "Files copied to docs/:"
          ls -R docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: false
          force_orphan: true