name: Publish Javadoc Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Generate Javadoc with Dokka
        run: |
          echo "Available Dokka tasks:"
          ./gradlew tasks --all | grep -i dokka || true
          echo "Generating documentation for Java sources..."
          
          # Try different Dokka tasks that work with Java
          ./gradlew dokkaJavadoc --stacktrace --console=plain || true
          ./gradlew dokkaGeneratePublicationJavadoc --stacktrace --console=plain || true
          
          # Also try standard Gradle javadoc task as fallback
          ./gradlew javadoc --stacktrace --console=plain || true

      - name: Find and prepare documentation
        run: |
          echo "Searching for generated documentation..."
          
          # Common Dokka output locations for Java
          POSSIBLE_LOCATIONS=(
            "build/dokka/javadoc"
            "build/dokka/html"
            "build/docs/javadoc"
            "build/documentation/javadoc"
            "build/javadoc"
          )
          
          DOCS_FOUND=false
          mkdir -p docs
          
          for location in "${POSSIBLE_LOCATIONS[@]}"; do
            if [ -d "$location" ]; then
              echo "Checking location: $location"
              ls -la "$location" || true
          
              # Check if there are actual HTML files (not just config files)
              HTML_COUNT=$(find "$location" -name "*.html" -type f | wc -l)
          
              if [ "$HTML_COUNT" -gt 0 ]; then
                echo "Found $HTML_COUNT HTML files in: $location"
                cp -r "$location"/* docs/
                DOCS_FOUND=true
                break
              else
                echo "No HTML files found in: $location"
              fi
            fi
          done
          
          if [ "$DOCS_FOUND" = false ]; then
            echo "Searching for any HTML files in entire build directory..."
            find build -name "*.html" -type f | head -10
          
            # Try to find any documentation directory with HTML files
            DOC_DIR=$(find build -name "*.html" -type f | head -1 | xargs dirname 2>/dev/null)
          
            if [ -n "$DOC_DIR" ] && [ -d "$DOC_DIR" ]; then
              echo "Found documentation directory with HTML: $DOC_DIR"
              cp -r "$DOC_DIR"/* docs/
              DOCS_FOUND=true
            fi
          fi
          
          if [ "$DOCS_FOUND" = false ]; then
            echo "No documentation found, creating placeholder..."
            mkdir -p docs
            cat > docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <title>OctoFault Documentation</title>
            <style>
              body { font-family: sans-serif; margin: 40px; background: #f5f5f5; }
              .container { max-width: 800px; margin: 0 auto; background: white; padding: 40px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }
              .warning { color: #f57c00; background: #fff3e0; padding: 20px; border-radius: 4px; margin: 20px 0; }
              .info { color: #1976d2; background: #e3f2fd; padding: 20px; border-radius: 4px; margin: 20px 0; }
              pre { background: #f5f5f5; padding: 15px; overflow-x: auto; border-radius: 4px; }
              h1 { color: #333; margin-top: 0; }
            </style>
          </head>
          <body>
            <div class="container">
              <h1>OctoFault Documentation</h1>
              <div class="warning">
                <h3>Documentation Not Generated</h3>
                <p>Dokka was unable to generate documentation. This usually means:</p>
                <ul>
                  <li>No public classes or methods found to document</li>
                  <li>Missing KDoc comments on public APIs</li>
                  <li>Dokka configuration needs adjustment</li>
                </ul>
              </div>
              <div class="info">
                <h3>To fix this:</h3>
                <ol>
                  <li>Add KDoc comments to your public classes and methods</li>
                  <li>Ensure your library has public APIs to document</li>
                  <li>Check the GitHub Actions logs for specific errors</li>
                </ol>
              </div>
              <p><strong>Repository:</strong> <a href="https://github.com/IKKNIGHT/Octofault">IKKNIGHT/Octofault</a></p>
            </div>
          </body>
          </html>
          EOF
          fi
          
          # Disable Jekyll processing
          touch docs/.nojekyll
          
          echo "Final documentation structure:"
          ls -la docs/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4