name: Publish Documentation

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Generate Documentation
        run: |
          # Generate docs using the module task
          ./gradlew dokkaGenerateModuleHTML

      - name: Locate and Copy Documentation
        run: |
          # Specific path found in your error log
          DOCS_PATH="build/dokka-module/html/module"
          
          if [ -d "$DOCS_PATH" ]; then
            echo "Found documentation at: $DOCS_PATH"
            mkdir -p docs
            cp -R "$DOCS_PATH"/* docs/
          else
            echo "Documentation not found! Directory structure:"
            find build -type d
            exit 1
          fi
          
          # Create necessary files for GitHub Pages
          touch docs/.nojekyll
          echo "# Documentation" > docs/README.md
          echo "Automatically generated documentation: [View Docs](index.html)" >> docs/README.md

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: false
          force_orphan: true