name: Publish Documentation

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Generate Documentation
        run: |
          # Run all possible Dokka tasks
          ./gradlew dokkaGenerateModuleHTML dokkaGeneratePublicationHTML dokkaGenerate || true
          echo "Dokka generation completed"

      - name: Find and Copy Documentation
        run: |
          # Check all possible Dokka output locations
          POSSIBLE_PATHS=(
            "build/dokka"
            "build/dokka/html"
            "build/dokka-module"
            "build/dokka-module/html"
            "build/reports/dokka"
            "build/docs/dokka"
            "build/dokka-publication"
          )
          
          FOUND=0
          for path in "${POSSIBLE_PATHS[@]}"; do
            if [ -d "$path" ]; then
              echo "Found documentation at: $path"
              mkdir -p docs
              cp -R "$path/." docs/
              FOUND=1
              break
            fi
          done
          
          if [ "$FOUND" -eq 0 ]; then
            echo "WARNING: No documentation found in standard locations!"
            echo "Searching entire build directory for HTML files..."
            find build -name '*.html' -exec cp --parents {} docs/ \;
          
            if [ ! -f "docs/index.html" ]; then
              echo "Creating placeholder documentation"
              echo "<html><body><h1>Documentation Not Found</h1><p>Check workflow logs for details</p></body></html>" > docs/index.html
            fi
          fi
          
          # Create necessary files for GitHub Pages
          touch docs/.nojekyll
          echo "# Documentation" > docs/README.md
          echo "Automatically generated documentation: [View Docs](index.html)" >> docs/README.md

      - name: Verify Documentation Files
        run: |
          echo "Documentation files in docs/:"
          ls -R docs || true
          echo "HTML files found: $(find docs -name '*.html' | wc -l)"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: false
          force_orphan: true