name: Publish Documentation

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Generate Documentation
        run: |
          ./gradlew dokkaGenerateModuleHtml --stacktrace || \
          { 
            echo "::error::Dokka generation failed!";
            exit 1;
          }

      - name: Copy Documentation
        run: |
          mkdir -p docs
          # Try multiple possible output locations
          cp -R build/dokka-module/html/module/* docs/ || \
          cp -R build/dokka/html/* docs/ || \
          cp -R build/dokka/* docs/ || \
          { 
            echo "::error::Documentation not found!";
            find build -name 'dokka*' -print;
            exit 1;
          }
          
          touch docs/.nojekyll
          echo "# Documentation" > docs/README.md
          echo "Automatically generated documentation: [View Docs](index.html)" >> docs/README.md
          echo "Files copied to docs/:"
          ls -R docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: false
          force_orphan: true