# Alternative approaches for the "Generate Documentation" step:

# Option 1: Try the module HTML generation
- name: Generate Documentation (Module HTML)
  run: |
    ./gradlew dokkaGenerateModuleHtml --stacktrace --console=plain
    echo "Dokka module HTML generation completed"

# Option 2: Try the standard dokka task
- name: Generate Documentation (Standard)
  run: |
    ./gradlew dokkaGenerate --stacktrace --console=plain
    echo "Dokka generation completed"

# Option 3: Try Javadoc generation
- name: Generate Documentation (Javadoc)
  run: |
    ./gradlew dokkaGeneratePublicationJavadoc --stacktrace --console=plain
    echo "Dokka Javadoc generation completed"

# Option 4: Multiple formats
- name: Generate Documentation (Multiple Formats)
  run: |
    ./gradlew dokkaGeneratePublicationHtml dokkaGeneratePublicationJavadoc --stacktrace --console=plain
    echo "Dokka generation completed"