name: Publish Documentation

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Grant execute permission for Gradle
        run: chmod +x gradlew
        
      - name: Generate Documentation
        run: ./gradlew dairyDokkaHtml
        
      - name: Prepare Docs Directory
        run: |
          mkdir -p docs
          cp -R build/dokka/html/* docs/
          touch docs/.nojekyll  # Critical for Jekyll disable
          echo "Documentation for $(git rev-parse --short HEAD)" > docs/README.md
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: false  # Clean previous deployments
